//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadThai
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThaiSQLEntities : DbContext
    {
        public ThaiSQLEntities()
            : base("name=ThaiSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Words2> Words2 { get; set; }
        public virtual DbSet<Sentence> Sentences { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<Paragraph> Paragraphs { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<CourseChapter> CourseChapters { get; set; }
        public virtual DbSet<ViewWord> ViewWords { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<ParagraphTranslationEnglish> ParagraphTranslationEnglishes { get; set; }
        public virtual DbSet<ParagraphSoundUrl> ParagraphSoundUrls { get; set; }
        public virtual DbSet<Timing> Timings { get; set; }
        public virtual DbSet<SentenceTranslationEnglish> SentenceTranslationEnglishes { get; set; }
    }
}
