//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadThai
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentenceTranslationEnglish
    {
        public int SentenceID { get; set; }
        public string Translation { get; set; }
    }
}
