//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadThai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timing
    {
        public int ParagraphID { get; set; }
        public int Timing1 { get; set; }
        public int Milliseconds { get; set; }
    }
}
