//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadThai
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewWord
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public Nullable<int> IDNecTec { get; set; }
        public string PBT { get; set; }
    }
}
