//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IReadThai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words2
    {
        public int id { get; set; }
        public string Word { get; set; }
        public string ShortTranslation { get; set; }
        public string EnglishTranslation { get; set; }
        public string L2Translation { get; set; }
        public string Examples { get; set; }
        public string MP3File { get; set; }
        public bool OriginalWord { get; set; }
    }
}
